import { summarizeBlockers } from '../blocker-analytics.js';
import { TrialBacktestReport } from '../backtest-trial.js';

function makeReport(dailyRecords: TrialBacktestReport['dailyRecords']): TrialBacktestReport {
  return {
    config: {
      ticker: 'AAPL',
      startDate: '2026-03-01',
      endDate: '2026-03-31',
      initialCapitalUsd: 10_000,
      mode: 'long_only',
      execution: 'next_open',
      dataRouting: {
        priceProvider: 'cache_yahoo_paid_fallback',
        fundamentalsProvider: 'paid_cached',
      },
      apiDelayMs: 0,
      fundamentalRefreshDays: 7,
      valuationRefreshDays: 7,
      sentimentRefreshDays: 3,
      dataQualityMaxFallbackRate: 0.2,
      signalProfile: 'adaptive',
      adaptiveLookbackDays: 30,
      adaptiveMinSamples: 10,
      adaptiveBuyQuantile: 0.78,
      adaptiveSellQuantile: 0.2,
      adaptiveEntryBuffer: 0.015,
      adaptiveCommitteeBuyRelief: 0.03,
      adaptiveBuyScoreFloor: -0.14,
      adaptiveAddScoreImprovementMin: 0.01,
      tacticalDipEnabled: true,
      tacticalRsiMax: 42,
      tacticalZScoreMax: -0.7,
      tacticalTrendScoreMin: -0.2,
      tacticalMinRiskScore: 0.55,
      tacticalMaxAggregateScore: 0.05,
      tacticalMinEdgeAfterCostsBps: 8,
      exitStopLossPct: 2.5,
      exitTakeProfitPct: 4.5,
      exitMaxHoldTradingDays: 7,
      adaptiveMinExpectedEdgeAfterCostsBps: 20,
      mlPredictionsCsvPath: null,
      mlBuyProbabilityThreshold: 0.58,
      mlSellProbabilityThreshold: 0.42,
      mlMinRiskScore: 0.3,
      mlPositionScale: 0.5,
    },
    generatedAt: '2026-04-10T00:00:00.000Z',
    summary: {
      totalReturnPct: 0,
      netPnlUsd: 0,
      maxDrawdownPct: 0,
      trades: 0,
      winRatePct: null,
      averageWinPct: null,
      averageLossPct: null,
      turnoverPct: 0,
      totalCostsUsd: 0,
      benchmarkReturnPct: null,
      fallbackTradingDays: 0,
      fallbackRatePct: 0,
      dataQualityStatus: 'pass',
      dataQualityNote: 'ok',
      holdTradingDays: 0,
      noSignalTradingDays: 0,
      nearBuyDays: 0,
      nearSellDays: 0,
      cacheHitRate: 0,
      apiCallsByEndpoint: [],
    },
    executionRows: [],
    dailyRecords,
  };
}

describe('blocker analytics summary', () => {
  test('aggregates HOLD blockers by month and overall', () => {
    const report = makeReport([
      {
        date: '2026-01-02',
        isTradingDay: true,
        marketClosed: false,
        signalAction: 'HOLD',
        normalizedAction: 'HOLD',
        actionNote: '',
        executedAction: 'HOLD',
        executionPrice: null,
        closePrice: 100,
        shares: 0,
        cashUsd: 10_000,
        positionValueUsd: 0,
        equityUsd: 10_000,
        dailyPnlUsd: 0,
        cumulativePnlUsd: 0,
        drawdownPct: 0,
        realizedPnlUsd: 0,
        unrealizedPnlUsd: 0,
        fallbackUsed: false,
        aggregateScore: 0,
        riskScore: 0,
        confidence: 0,
        buyScoreGap: 0,
        buyRiskGap: 0,
        sellScoreGap: 0,
        longExitGap: 0,
        primaryBlocker: 'Aggregate score in HOLD zone',
        blockersTop3: ['Aggregate score in HOLD zone'],
        alphaLaneScore: 0,
        contextLaneScore: 0,
      },
      {
        date: '2026-01-03',
        isTradingDay: true,
        marketClosed: false,
        signalAction: 'HOLD',
        normalizedAction: 'HOLD',
        actionNote: '',
        executedAction: 'HOLD',
        executionPrice: null,
        closePrice: 100,
        shares: 0,
        cashUsd: 10_000,
        positionValueUsd: 0,
        equityUsd: 10_000,
        dailyPnlUsd: 0,
        cumulativePnlUsd: 0,
        drawdownPct: 0,
        realizedPnlUsd: 0,
        unrealizedPnlUsd: 0,
        fallbackUsed: false,
        aggregateScore: 0,
        riskScore: 0,
        confidence: 0,
        buyScoreGap: 0,
        buyRiskGap: 0,
        sellScoreGap: 0,
        longExitGap: 0,
        primaryBlocker: 'NO_SIGNAL: expected edge after costs below minimum',
        blockersTop3: ['NO_SIGNAL: expected edge after costs below minimum'],
        alphaLaneScore: 0,
        contextLaneScore: 0,
      },
      {
        date: '2026-02-04',
        isTradingDay: true,
        marketClosed: false,
        signalAction: 'BUY',
        normalizedAction: 'BUY',
        actionNote: '',
        executedAction: 'HOLD',
        executionPrice: null,
        closePrice: 100,
        shares: 0,
        cashUsd: 10_000,
        positionValueUsd: 0,
        equityUsd: 10_000,
        dailyPnlUsd: 0,
        cumulativePnlUsd: 0,
        drawdownPct: 0,
        realizedPnlUsd: 0,
        unrealizedPnlUsd: 0,
        fallbackUsed: false,
        aggregateScore: 0,
        riskScore: 0,
        confidence: 0,
        buyScoreGap: 0,
        buyRiskGap: 0,
        sellScoreGap: 0,
        longExitGap: 0,
        primaryBlocker: 'No blocker',
        blockersTop3: ['No blocker'],
        alphaLaneScore: 0,
        contextLaneScore: 0,
      },
    ]);

    const summary = summarizeBlockers([report], 3);
    expect(summary.overall.tradingDays).toBe(3);
    expect(summary.overall.holdDays).toBe(2);
    expect(summary.overall.noSignalDays).toBe(1);
    expect(summary.overall.topBlockers[0].count).toBe(1);
    expect(summary.monthly.find((month) => month.month === '2026-01')?.holdDays).toBe(2);
  });
});
